# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: txn.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from object import expr_pb2 as object_dot_expr__pb2
from object import value_pb2 as object_dot_value__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='txn.proto',
  package='engula.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ttxn.proto\x12\tengula.v1\x1a\x11object/expr.proto\x1a\x12object/value.proto\"B\n\x0f\x42\x61tchTxnRequest\x12/\n\x08requests\x18\x01 \x03(\x0b\x32\x1d.engula.v1.DatabaseTxnRequest\"E\n\x10\x42\x61tchTxnResponse\x12\x31\n\tresponses\x18\x01 \x03(\x0b\x32\x1e.engula.v1.DatabaseTxnResponse\"U\n\x12\x44\x61tabaseTxnRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x31\n\x08requests\x18\x02 \x03(\x0b\x32\x1f.engula.v1.CollectionTxnRequest\"J\n\x13\x44\x61tabaseTxnResponse\x12\x33\n\tresponses\x18\x01 \x03(\x0b\x32 .engula.v1.CollectionTxnResponse\"D\n\x14\x43ollectionTxnRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1e\n\x05\x65xprs\x18\x02 \x03(\x0b\x32\x0f.engula.v1.Expr\"?\n\x15\x43ollectionTxnResponse\x12&\n\x07results\x18\x01 \x03(\x0b\x32\x15.engula.v1.ExprResult2I\n\x03Txn\x12\x42\n\x05\x42\x61tch\x12\x1a.engula.v1.BatchTxnRequest\x1a\x1b.engula.v1.BatchTxnResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[object_dot_expr__pb2.DESCRIPTOR,object_dot_value__pb2.DESCRIPTOR,])




_BATCHTXNREQUEST = _descriptor.Descriptor(
  name='BatchTxnRequest',
  full_name='engula.v1.BatchTxnRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='requests', full_name='engula.v1.BatchTxnRequest.requests', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=129,
)


_BATCHTXNRESPONSE = _descriptor.Descriptor(
  name='BatchTxnResponse',
  full_name='engula.v1.BatchTxnResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='responses', full_name='engula.v1.BatchTxnResponse.responses', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=200,
)


_DATABASETXNREQUEST = _descriptor.Descriptor(
  name='DatabaseTxnRequest',
  full_name='engula.v1.DatabaseTxnRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='engula.v1.DatabaseTxnRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='requests', full_name='engula.v1.DatabaseTxnRequest.requests', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=287,
)


_DATABASETXNRESPONSE = _descriptor.Descriptor(
  name='DatabaseTxnResponse',
  full_name='engula.v1.DatabaseTxnResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='responses', full_name='engula.v1.DatabaseTxnResponse.responses', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=289,
  serialized_end=363,
)


_COLLECTIONTXNREQUEST = _descriptor.Descriptor(
  name='CollectionTxnRequest',
  full_name='engula.v1.CollectionTxnRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='engula.v1.CollectionTxnRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='exprs', full_name='engula.v1.CollectionTxnRequest.exprs', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=365,
  serialized_end=433,
)


_COLLECTIONTXNRESPONSE = _descriptor.Descriptor(
  name='CollectionTxnResponse',
  full_name='engula.v1.CollectionTxnResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='results', full_name='engula.v1.CollectionTxnResponse.results', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=435,
  serialized_end=498,
)

_BATCHTXNREQUEST.fields_by_name['requests'].message_type = _DATABASETXNREQUEST
_BATCHTXNRESPONSE.fields_by_name['responses'].message_type = _DATABASETXNRESPONSE
_DATABASETXNREQUEST.fields_by_name['requests'].message_type = _COLLECTIONTXNREQUEST
_DATABASETXNRESPONSE.fields_by_name['responses'].message_type = _COLLECTIONTXNRESPONSE
_COLLECTIONTXNREQUEST.fields_by_name['exprs'].message_type = object_dot_expr__pb2._EXPR
_COLLECTIONTXNRESPONSE.fields_by_name['results'].message_type = object_dot_expr__pb2._EXPRRESULT
DESCRIPTOR.message_types_by_name['BatchTxnRequest'] = _BATCHTXNREQUEST
DESCRIPTOR.message_types_by_name['BatchTxnResponse'] = _BATCHTXNRESPONSE
DESCRIPTOR.message_types_by_name['DatabaseTxnRequest'] = _DATABASETXNREQUEST
DESCRIPTOR.message_types_by_name['DatabaseTxnResponse'] = _DATABASETXNRESPONSE
DESCRIPTOR.message_types_by_name['CollectionTxnRequest'] = _COLLECTIONTXNREQUEST
DESCRIPTOR.message_types_by_name['CollectionTxnResponse'] = _COLLECTIONTXNRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BatchTxnRequest = _reflection.GeneratedProtocolMessageType('BatchTxnRequest', (_message.Message,), {
  'DESCRIPTOR' : _BATCHTXNREQUEST,
  '__module__' : 'txn_pb2'
  # @@protoc_insertion_point(class_scope:engula.v1.BatchTxnRequest)
  })
_sym_db.RegisterMessage(BatchTxnRequest)

BatchTxnResponse = _reflection.GeneratedProtocolMessageType('BatchTxnResponse', (_message.Message,), {
  'DESCRIPTOR' : _BATCHTXNRESPONSE,
  '__module__' : 'txn_pb2'
  # @@protoc_insertion_point(class_scope:engula.v1.BatchTxnResponse)
  })
_sym_db.RegisterMessage(BatchTxnResponse)

DatabaseTxnRequest = _reflection.GeneratedProtocolMessageType('DatabaseTxnRequest', (_message.Message,), {
  'DESCRIPTOR' : _DATABASETXNREQUEST,
  '__module__' : 'txn_pb2'
  # @@protoc_insertion_point(class_scope:engula.v1.DatabaseTxnRequest)
  })
_sym_db.RegisterMessage(DatabaseTxnRequest)

DatabaseTxnResponse = _reflection.GeneratedProtocolMessageType('DatabaseTxnResponse', (_message.Message,), {
  'DESCRIPTOR' : _DATABASETXNRESPONSE,
  '__module__' : 'txn_pb2'
  # @@protoc_insertion_point(class_scope:engula.v1.DatabaseTxnResponse)
  })
_sym_db.RegisterMessage(DatabaseTxnResponse)

CollectionTxnRequest = _reflection.GeneratedProtocolMessageType('CollectionTxnRequest', (_message.Message,), {
  'DESCRIPTOR' : _COLLECTIONTXNREQUEST,
  '__module__' : 'txn_pb2'
  # @@protoc_insertion_point(class_scope:engula.v1.CollectionTxnRequest)
  })
_sym_db.RegisterMessage(CollectionTxnRequest)

CollectionTxnResponse = _reflection.GeneratedProtocolMessageType('CollectionTxnResponse', (_message.Message,), {
  'DESCRIPTOR' : _COLLECTIONTXNRESPONSE,
  '__module__' : 'txn_pb2'
  # @@protoc_insertion_point(class_scope:engula.v1.CollectionTxnResponse)
  })
_sym_db.RegisterMessage(CollectionTxnResponse)



_TXN = _descriptor.ServiceDescriptor(
  name='Txn',
  full_name='engula.v1.Txn',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=500,
  serialized_end=573,
  methods=[
  _descriptor.MethodDescriptor(
    name='Batch',
    full_name='engula.v1.Txn.Batch',
    index=0,
    containing_service=None,
    input_type=_BATCHTXNREQUEST,
    output_type=_BATCHTXNRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TXN)

DESCRIPTOR.services_by_name['Txn'] = _TXN

# @@protoc_insertion_point(module_scope)
