# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import txn_pb2 as txn__pb2


class TxnStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Batch = channel.unary_unary(
                '/engula.v1.Txn/Batch',
                request_serializer=txn__pb2.BatchTxnRequest.SerializeToString,
                response_deserializer=txn__pb2.BatchTxnResponse.FromString,
                )


class TxnServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Batch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TxnServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Batch': grpc.unary_unary_rpc_method_handler(
                    servicer.Batch,
                    request_deserializer=txn__pb2.BatchTxnRequest.FromString,
                    response_serializer=txn__pb2.BatchTxnResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'engula.v1.Txn', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Txn(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Batch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/engula.v1.Txn/Batch',
            txn__pb2.BatchTxnRequest.SerializeToString,
            txn__pb2.BatchTxnResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
