# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import universe_pb2 as universe__pb2


class UniverseStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Database = channel.unary_unary(
                '/engula.v1.Universe/Database',
                request_serializer=universe__pb2.DatabaseRequest.SerializeToString,
                response_deserializer=universe__pb2.DatabaseResponse.FromString,
                )
        self.Collection = channel.unary_unary(
                '/engula.v1.Universe/Collection',
                request_serializer=universe__pb2.CollectionRequest.SerializeToString,
                response_deserializer=universe__pb2.CollectionResponse.FromString,
                )


class UniverseServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Database(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Collection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UniverseServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Database': grpc.unary_unary_rpc_method_handler(
                    servicer.Database,
                    request_deserializer=universe__pb2.DatabaseRequest.FromString,
                    response_serializer=universe__pb2.DatabaseResponse.SerializeToString,
            ),
            'Collection': grpc.unary_unary_rpc_method_handler(
                    servicer.Collection,
                    request_deserializer=universe__pb2.CollectionRequest.FromString,
                    response_serializer=universe__pb2.CollectionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'engula.v1.Universe', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Universe(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Database(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/engula.v1.Universe/Database',
            universe__pb2.DatabaseRequest.SerializeToString,
            universe__pb2.DatabaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Collection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/engula.v1.Universe/Collection',
            universe__pb2.CollectionRequest.SerializeToString,
            universe__pb2.CollectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
